cityofaustin/atd-product

public/index.html

Sorry for the multiple PRs!
(Again) fixes https://github.com/cityofaustin/atd-data-tech/issues/4635
Regenerated tags using hey meta

regenerated tags using hey meta

---

src/views/aboutView/AboutView.jsx

Fixes https://github.com/cityofaustin/atd-data-tech/issues/4805

updated pronouns

---

src/views/aboutView/AboutView.jsx

Fixes https://github.com/cityofaustin/atd-data-tech/issues/5181

add Amenity, remove Jace

---

src/views/aboutView/AboutView.jsx

Fixes https://github.com/cityofaustin/atd-data-tech/issues/5395

updated Amenity's title

---

package-lock.json
package.json
src/scss/custom.scss
src/shared/NavComponent.jsx

- Closes https://github.com/cityofaustin/atd-data-tech/issues/6279
- Removes horizontal scroll for About us, What we deliver, and Our work pages.

Jg 6279 fix horizontal scroll

---

components/shared/indexIssueDetails/IndexIssueDetails.js

Fixes [#7298](https://github.com/cityofaustin/atd-data-tech/issues/7298).
I can't re-produce this exact behavior locally or in a deploy preview, but I was able to force the same error by manually setting issue to `undefined` and by setting an invalid project ID in the URL. 
In any case, it is fixed.

7298 Resolves unhandled error when loading index issue details page

---

pages/about/index.js

Members are ordered by their longevity with ATD, plus me

Fix team member ordering

---

pages/about/index.js

Move SG to Alumni

---

pages/about/index.js

This PR moves Jaime into the Alumni section of the team's website.

Add Jaime to alumni section

---

pages/about/index.js

https://github.com/cityofaustin/atd-data-tech/issues/9091
This PR adds me back to the current team on the About Us page on the DTS site.
**URL to test:** 
https://deploy-preview-35--atd-product.netlify.app/about
**Steps to test:**
Go to the link above and see Mike D. moved from alumni to current team
---

Add Mike D. back to the About Us section

---

pages/about/index.js

This resolves [#10075](https://github.com/cityofaustin/atd-data-tech/issues/10075) to move Rebecca B from 'Our team' to 'Alumni' section.
Review Link: https://deploy-preview-45--atd-product.netlify.app/about

Moved Rebecca B to Alumni Section

---

pages/about/index.js

https://deploy-preview-46--atd-product.netlify.app/about#team
https://github.com/cityofaustin/atd-data-tech/issues/10255
and closes: https://github.com/cityofaustin/atd-data-tech/issues/5554

Update titles and add anchor tags

---

components/shared/NavComponent.js
components/shared/Page.js
pages/index.js

This PR changes the hero title on the home page from "Tech Support" to "Digital Services" and also adds a navbar shadow to all of the pages except for the home page to match https://data.mobility.austin.gov/

Change hero title and add nav shadow

---

pages/about/index.js

https://deploy-preview-58--atd-product.netlify.app/about

move alan to alumni

---

pages/CustomHead.js
pages/index.js

This PR closes [#13710](https://github.com/cityofaustin/atd-data-tech/issues/13710), which will update the hero text and metadata to align with TPW.
- [Link ](https://deploy-preview-76--atd-product.netlify.app/)
- Confirm that h1 hero text says "Data & Technology Services"
- Confirm metadata reads "Austin Transportation Public Works Data & Technology Services"

Update hero text and metadata to reflect Austin Transportation Public Works

---

pages/about/index.js

https://github.com/cityofaustin/atd-data-tech/issues/14933
https://deploy-preview-81--atd-product.netlify.app/about

move Dipa to alumni section

---

pages/about/index.js

This closes https://github.com/cityofaustin/atd-data-tech/issues/16284
Confirm that Josh has been moved from `Meet the team` section to `Alumni `section.
[Link](https://deploy-preview-83--atd-product.netlify.app/about)

Move Josh to Alumni section of the DTS website

---

.gitignore
.prettierrc
components/utils.js
components/wrappers/IssuesContextWrapper.js

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/16252.
This PR adds `.vscode` to the root `.gitignore` file and defines a `.prettierrc` with a configuration designed to match the repos current style.
https://deploy-preview-86--atd-product.netlify.app/
You should not be able to see any ice-boxed issues anywhere on the site, however, this is not a great test because the index label is removed when things are ice-boxed.
I recommend spinning this up locally and modifying [this line](https://github.com/cityofaustin/atd-product/blob/a483580192d036f6fc1039defbd9984cae2cf750/components/utils.js#L92) to other pipelines states (`backlog` for example) and seeing the filtering work for that state.

Hide icebox issues

---

pages/about/index.js

https://github.com/cityofaustin/atd-data-tech/issues/18649
https://deploy-preview-96--atd-product.netlify.app/en/about

Moving Olivia and Arkadeep to Alumni section

---

pages/about/index.js

https://deploy-preview-99--atd-product.netlify.app/about#alumni

move Daniel to alum section

---

pages/about/index.js

https://deploy-preview-101--atd-product.netlify.app/about#alumni
Moved from Meet the Team to Alumni

Move Ganesh to alumni section

---

pages/about/index.js

closes https://github.com/cityofaustin/atd-data-tech/issues/21947
https://deploy-preview-102--atd-product.netlify.app/about#alumni

Move Patrick to alum section

---

package-lock.json
package.json
pages/about/index.js

https://deploy-preview-108--atd-product.netlify.app/about#alumni
Moved Will to the Alumni section, also removed some testing packages we dont use and updated the version of NextJS (There is a dependabot prompting us to update, https://github.com/cityofaustin/atd-product/pull/107, i went to the latest version)

Move Will to Alumni section
